"""add conversations and messages tables

Revision ID: 5b8be3bea51d
Revises: ef22178d09c9
Create Date: 2026-09-08 02:03:08.656224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8be3bea51d'
down_revision: Union[str, Sequence[str], None] = 'ef22178d09c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
